name: 'template'
version: '1.0.0'

profile: 'template_profile' # <-- Nome do profile (igual ao especificado em profiles.yml)

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  template:

    bronze:
      schema: "{% if target.name == 'prod' %}bronze{% else %}{{ target.schema }}_bronze{% endif %}"
      materialized: table
      tags: '[bronze]'

    silver:
      schema: "{% if target.name == 'prod' %}silver{% else %}{{ target.schema }}_silver{% endif %}"
      materialized: table
      tags: '[silver]'

    gold:
      schema: "{% if target.name == 'prod' %}gold{% else %}{{ target.schema }}_gold{% endif %}"
      materialized: table
      tags: '[gold]'

seeds:
  template:
    schema: raw
    tags: ['seed']

# on-run-end: "{% if target.name == 'pr' %} drop schema {{ target.schema }} cascade {% endif %}"