name: CD_action

on:
  push:
    branches:
      - main

jobs:
  CD_job:
    runs-on: ubuntu-latest

    env:
      GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
      GCLOUD_STORAGE_PATH_MANIFEST: ${{ secrets.GCLOUD_STORAGE_PATH_MANIFEST }} 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r dbt-requirements.txt

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.4.3
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - name: Extract project ID from service key
      id: extract_project
      run: echo "PROJECT_ID=$(echo '${{ secrets.GCLOUD_SERVICE_KEY }}' | jq -r '.project_id')" >> $GITHUB_ENV

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Copy manifest.json from Google Cloud Storage
      run: |
        gsutil cp gs://${{ env.GCLOUD_STORAGE_PATH_MANIFEST }}/manifest.json ./ || echo "Manifest not found"

    - name: Run dbt debug
      run: dbt debug --target prod

    - name: Run dbt deps
      run: dbt deps --target prod

    - name: Run dbt seed first
      run: |
        dbt seed --target prod

    - name: Run dbt models and tests
      run: |
        if [ -f "./manifest.json" ]; then
          dbt run -s 'state:modified+' --full-refresh --state ./ --target prod
          dbt test -s 'state:modified+' --state ./ --target prod
        else
          dbt run --target prod
          dbt test --target prod
        fi

    - name: Copy new manifest.json to Google Cloud Storage
      run: |
        gsutil cp ./target/manifest.json gs://${{ env.GCLOUD_STORAGE_PATH_MANIFEST }}/