name: CI_Teardown

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  cleanup_pr_schemas:
    runs-on: ubuntu-latest

    env:
      GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r dbt-requirements.txt

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.4.3
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - name: Extract project ID from service key
      id: extract_project
      run: echo "PROJECT_ID=$(echo '${{ secrets.GCLOUD_SERVICE_KEY }}' | jq -r '.project_id')" >> $GITHUB_ENV

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Drop PR schemas
      run: |
        echo "Cleaning up schemas for PR #${{ github.event.pull_request.number }}"
        dbt run-operation drop_pr_staging_schemas \
          --args '{"project_id": "${{ env.PROJECT_ID }}", "PR_number": "${{ github.event.pull_request.number }}"}' \
          --profiles-dir ./
      continue-on-error: true

    - name: Log cleanup completion
      run: |
        echo "PR schema cleanup completed for PR #${{ github.event.pull_request.number }}"