name: CI schema teardown on PR close

on:
  pull_request:
    types:
      - closed

jobs:
  CI_TEARDOWN_job:
    runs-on: ubuntu-latest

    env:
      GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r dbt-requirements.txt

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.4.3
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - name: Extract project ID from service key
      id: extract_project
      run: echo "PROJECT_ID=$(echo '${{ secrets.GCLOUD_SERVICE_KEY }}' | jq -r '.project_id')" >> $GITHUB_ENV

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Get PR NUM
      id: schema_id
      run: echo "PR_NUM=${{ github.event.number }}" >> $GITHUB_ENV

    - name: dbt deps
      run: dbt deps

    - name: drop PR schemas
      run: dbt run-operation drop_pr_staging_schemas --args "{'project_id'":" '${PROJECT_ID}', 'PR_number'":" '${PR_NUM}' }" --profiles-dir ./